-- AlterTable
ALTER TABLE `Otp` ADD COLUMN `attempts` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `lastAttemptAt` DATETIME(3) NULL,
    ADD COLUMN `lastSentAt` DATETIME(3) NULL,
    ADD COLUMN `resendCount` INTEGER NOT NULL DEFAULT 0,
    MODIFY `pin` VARCHAR(191) NOT NULL;
