-- AlterTable
ALTER TABLE `User` ADD COLUMN `offlineBalance` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `offlineLimit` DOUBLE NOT NULL DEFAULT 10,
    ADD COLUMN `onlineBalance` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `onlineLimit` DOUBLE NOT NULL DEFAULT 1000;
